# Generated by Django 4.2.6 on 2023-10-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_voted',
        ),
    ]
