# Generated by Django 4.2.6 on 2023-10-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='created_by',
        ),
    ]
