# Generated by Django 4.2.6 on 2023-10-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='full_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
