# Generated by Django 4.2.6 on 2023-10-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_choice_voted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voted_by',
        ),
    ]
