# Generated by Django 4.2.6 on 2023-10-20 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0017_alter_choice_voted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voted_by',
        ),
        migrations.AddField(
            model_name='choice',
            name='voted_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
